CREATE TABLE IF NOT EXISTS agenda (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    meeting_id INTEGER NOT NULL REFERENCES meetings(id),
    assigned_to INTEGER REFERENCES users(id),
    title VARCHAR(100) NOT NULL,
    description TEXT,
    due_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);